# .xinitrc

# Dual screen configuration
xrandr --auto --output DVI-0 --mode 1920x1080 --right-of HDMI-0 &

# Import configuration from .Xresources
xrdb -merge .Xresources

# PolicyKit daemon
#/usr/libexec/polkit-gnome-authentication-agent-1 &

# Gnome keyring daemon
#eval `/usr/bin/gnome-keyring-daemon --start --components=gpg,pkcs11,secrets,ssh`

# Start an i3 session
exec i3
